## Import external libraries

In [23]:
import pandas as pd
import numpy as np

## Load data

In [2]:
df = pd.read_csv("./train.csv")

In [3]:
df.head(5)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

## Inspect data

In [4]:
df.Sex.unique()

array(['male', 'female'], dtype=object)

In [5]:
df.Pclass.unique()

array([3, 1, 2], dtype=int64)

In [6]:
df.SibSp.unique()

array([1, 0, 3, 4, 2, 5, 8], dtype=int64)

In [7]:
df.Parch.unique()

array([0, 1, 2, 5, 3, 4, 6], dtype=int64)

In [8]:
df.Sex

0        male
1      female
2      female
3      female
4        male
5        male
6        male
7        male
8      female
9      female
10     female
11     female
12       male
13       male
14     female
15     female
16       male
17       male
18     female
19     female
20       male
21       male
22     female
23       male
24     female
25     female
26       male
27       male
28     female
29       male
        ...  
861      male
862    female
863    female
864      male
865    female
866    female
867      male
868      male
869      male
870      male
871    female
872      male
873      male
874    female
875    female
876      male
877      male
878      male
879    female
880    female
881      male
882    female
883      male
884      male
885    female
886      male
887    female
888    female
889      male
890      male
Name: Sex, Length: 891, dtype: object

In [9]:
df.groupby('SibSp').count()

PassengerId  Survived  Pclass  Name  Sex  Age  Parch  Ticket  Fare  \
SibSp                                                                       
0              608       608     608   608  608  471    608     608   608   
1              209       209     209   209  209  183    209     209   209   
2               28        28      28    28   28   25     28      28    28   
3               16        16      16    16   16   12     16      16    16   
4               18        18      18    18   18   18     18      18    18   
5                5         5       5     5    5    5      5       5     5   
8                7         7       7     7    7    0      7       7     7   

       Cabin  Embarked  
SibSp                   
0        126       606  
1         69       209  
2          6        28  
3          3        16  
4          0        18  
5          0         5  
8          0         7

In [10]:
df.SibSp.value_counts()

0    608
1    209
2     28
4     18
3     16
8      7
5      5
Name: SibSp, dtype: int64

In [11]:
df.isnull().values

array([[False, False, False, ..., False,  True, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False,  True, False],
       ..., 
       [False, False, False, ..., False,  True, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False,  True, False]], dtype=bool)

In [12]:
df.isnull().values.any()

True

In [13]:
df.head(5)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [14]:
df.corr()

PassengerId  Survived    Pclass       Age     SibSp     Parch  \
PassengerId     1.000000 -0.005007 -0.035144  0.036847 -0.057527 -0.001652   
Survived       -0.005007  1.000000 -0.338481 -0.077221 -0.035322  0.081629   
Pclass         -0.035144 -0.338481  1.000000 -0.369226  0.083081  0.018443   
Age             0.036847 -0.077221 -0.369226  1.000000 -0.308247 -0.189119   
SibSp          -0.057527 -0.035322  0.083081 -0.308247  1.000000  0.414838   
Parch          -0.001652  0.081629  0.018443 -0.189119  0.414838  1.000000   
Fare            0.012658  0.257307 -0.549500  0.096067  0.159651  0.216225   

                 Fare  
PassengerId  0.012658  
Survived     0.257307  
Pclass      -0.549500  
Age          0.096067  
SibSp        0.159651  
Parch        0.216225  
Fare         1.000000

## Transform data

In [15]:
df.loc[df['Sex'] == 'female', 'Sex'] = 1

In [16]:
df.head(5)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name   Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris  male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...     1  38.0      1   
2                             Heikkinen, Miss. Laina     1  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)     1  35.0      1   
4                           Allen, Mr. William Henry  male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [17]:
df.loc[df.Sex == 'male', 'Sex'] = 0

In [18]:
df.head(4)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   

                                                Name Sex   Age  SibSp  Parch  \
0                            Braund, Mr. Owen Harris   0  22.0      1      0   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...   1  38.0      1      0   
2                             Heikkinen, Miss. Laina   1  26.0      0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)   1  35.0      1      0   

             Ticket     Fare Cabin Embarked  
0         A/5 21171   7.2500   NaN        S  
1          PC 17599  71.2833   C85        C  
2  STON/O2. 3101282   7.9250   NaN        S  
3            113803  53.1000  C123        S

In [19]:
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [20]:
df.columns = ['PassengerId', 'Survived', 'Pclass', 'Name', 'IsFemale', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked']

In [21]:
df.head(5)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name IsFemale   Age  SibSp  \
0                            Braund, Mr. Owen Harris        0  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...        1  38.0      1   
2                             Heikkinen, Miss. Laina        1  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)        1  35.0      1   
4                           Allen, Mr. William Henry        0  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [22]:
df.Cabin.unique()

array([nan, 'C85', 'C123', 'E46', 'G6', 'C103', 'D56', 'A6', 'C23 C25 C27',
       'B78', 'D33', 'B30', 'C52', 'B28', 'C83', 'F33', 'F G73', 'E31',
       'A5', 'D10 D12', 'D26', 'C110', 'B58 B60', 'E101', 'F E69', 'D47',
       'B86', 'F2', 'C2', 'E33', 'B19', 'A7', 'C49', 'F4', 'A32', 'B4',
       'B80', 'A31', 'D36', 'D15', 'C93', 'C78', 'D35', 'C87', 'B77',
       'E67', 'B94', 'C125', 'C99', 'C118', 'D7', 'A19', 'B49', 'D',
       'C22 C26', 'C106', 'C65', 'E36', 'C54', 'B57 B59 B63 B66', 'C7',
       'E34', 'C32', 'B18', 'C124', 'C91', 'E40', 'T', 'C128', 'D37',
       'B35', 'E50', 'C82', 'B96 B98', 'E10', 'E44', 'A34', 'C104', 'C111',
       'C92', 'E38', 'D21', 'E12', 'E63', 'A14', 'B37', 'C30', 'D20',
       'B79', 'E25', 'D46', 'B73', 'C95', 'B38', 'B39', 'B22', 'C86',
       'C70', 'A16', 'C101', 'C68', 'A10', 'E68', 'B41', 'A20', 'D19',
       'D50', 'D9', 'A23', 'B50', 'A26', 'D48', 'E58', 'C126', 'B71',
       'B51 B53 B55', 'D49', 'B5', 'B20', 'F G63', 'C62 C64', 'E24',

In [24]:
df.HadCabin = np.where(df.Cabin.isnull(), 0, 1)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name IsFemale   Age  SibSp  \
0                            Braund, Mr. Owen Harris        0  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...        1  38.0      1   
2                             Heikkinen, Miss. Laina        1  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)        1  35.0      1   
4                           Allen, Mr. William Henry        0  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [26]:
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'IsFemale', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [27]:
df['HadCabin'] = np.where(df['Cabin'].isnull(), 0, 1)

In [29]:
df.head(50)

PassengerId  Survived  Pclass  \
0             1         0       3   
1             2         1       1   
2             3         1       3   
3             4         1       1   
4             5         0       3   
5             6         0       3   
6             7         0       1   
7             8         0       3   
8             9         1       3   
9            10         1       2   
10           11         1       3   
11           12         1       1   
12           13         0       3   
13           14         0       3   
14           15         0       3   
15           16         1       2   
16           17         0       3   
17           18         1       2   
18           19         0       3   
19           20         1       3   
20           21         0       2   
21           22         1       2   
22           23         1       3   
23           24         1       1   
24           25         0       3   
25           26         1       3   
26           27         0       3   
27           28         0       1   
28           29         1       3   
29           30         0       3   
30           31         0       1   
31           32         1       1   
32           33         1       3   
33           34         0       2   
34           35         0       1   
35           36         0       1   
36           37         1       3   
37           38         0       3   
38           39         0       3   
39           40         1       3   
40           41         0       3   
41           42         0       2   
42           43         0       3   
43           44         1       2   
44           45         1       3   
45           46         0       3   
46           47         0       3   
47           48         1       3   
48           49         0       3   
49           50         0       3   

                                                 Name IsFemale   Age  SibSp  \
0                             Braund, Mr. Owen Harris        0  22.0      1   
1   Cumings, Mrs. John Bradley (Florence Briggs Th...        1  38.0      1   
2                              Heikkinen, Miss. Laina        1  26.0      0   
3        Futrelle, Mrs. Jacques Heath (Lily May Peel)        1  35.0      1   
4                            Allen, Mr. William Henry        0  35.0      0   
5                                    Moran, Mr. James        0   NaN      0   
6                             McCarthy, Mr. Timothy J        0  54.0      0   
7                      Palsson, Master. Gosta Leonard        0   2.0      3   
8   Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)        1  27.0      0   
9                 Nasser, Mrs. Nicholas (Adele Achem)        1  14.0      1   
10                    Sandstrom, Miss. Marguerite Rut        1   4.0      1   
11                           Bonnell, Miss. Elizabeth        1  58.0      0   
12                     Saundercock, Mr. William Henry        0  20.0      0   
13                        Andersson, Mr. Anders Johan        0  39.0      1   
14               Vestrom, Miss. Hulda Amanda Adolfina        1  14.0      0   
15                   Hewlett, Mrs. (Mary D Kingcome)         1  55.0      0   
16                               Rice, Master. Eugene        0   2.0      4   
17                       Williams, Mr. Charles Eugene        0   NaN      0   
18  Vander Planke, Mrs. Julius (Emelia Maria Vande...        1  31.0      1   
19                            Masselmani, Mrs. Fatima        1   NaN      0   
20                               Fynney, Mr. Joseph J        0  35.0      0   
21                              Beesley, Mr. Lawrence        0  34.0      0   
22                        McGowan, Miss. Anna "Annie"        1  15.0      0   
23                       Sloper, Mr. William Thompson        0  28.0      0   
24                      Palsson, Miss. Torborg Danira        1   8.0      3   
25  Asplund, Mrs. Carl Oscar (Selma Augusta Emilia...        1